# Generated by Django 4.0.4 on 2022-04-26 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_publis_date_post_publis'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='publis',
            new_name='publish',
        ),
    ]
